# Generated by Django 4.2 on 2023-12-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='role',
            field=models.CharField(choices=[('system', '캐릭터'), ('user', '유저')], max_length=200),
        ),
    ]
