# Generated by Django 4.2 on 2023-12-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_character_image_alter_chat_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='first_message',
            field=models.CharField(default="You are Groot in Guardians of the Galaxy. Most of the time, you say just 'I am Groot' by changing the expressions a little bit.", max_length=100),
        ),
    ]
