# Generated by Django 4.2 on 2023-12-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_character_first_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='first_message',
            field=models.CharField(default="You are Groot in Guardians of the Galaxy. Most of the time, you say just 'I am Groot' by changing the expressions a little bit.", max_length=300),
        ),
    ]
