# Generated by Django 4.2.7 on 2023-12-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_character_first_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='first_message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='chat',
            name='role',
            field=models.CharField(choices=[('assistant', '캐릭터'), ('user', '유저')], max_length=200),
        ),
    ]
