# Generated by Django 4.2.7 on 2023-12-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_character_first_message_alter_chat_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.FileField(upload_to='media/groot.png'),
        ),
    ]
