# Generated by Django 4.0 on 2023-12-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chracter_image_upload_dir_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(upload_to='bot/chracters/images/'),
        ),
    ]
