# Generated by Django 2.2 on 2023-11-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='review',
            new_name='post',
        ),
    ]
