# Generated by Django 5.0 on 2023-12-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
