branch-defaults:
  assignment-01-aws:
    environment: django-env
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: portfolio_project
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
