# Generated by Django 4.2.7 on 2023-11-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
