# Generated by Django 4.2.7 on 2023-11-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
