# Generated by Django 4.2.7 on 2023-11-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_is_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('content', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_tags',
            field=models.ManyToManyField(blank=True, help_text='태그는 해시태그(#)로 분리해서 적어주세요.', to='posts.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='태그는 해시태그(#)로 분리해서 적어주세요.', to='posts.tag'),
        ),
    ]
