# Generated by Django 4.2.7 on 2023-11-08 02:27

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_auther_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[blog.validators.content_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[blog.validators.content_validator, blog.validators.validate_no_special_characters]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[blog.validators.title_validator]),
        ),
    ]
