# Generated by Django 4.2.7 on 2023-11-08 09:46

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_post_alter_comment_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다. '}, max_length=15, unique=True, validators=[blog.validators.validate_no_special_characters]),
        ),
    ]
