# Generated by Django 3.2.21 on 2023-11-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성 시각'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시각'),
        ),
    ]
