# Generated by Django 3.2.21 on 2023-11-22 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231122_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=300, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성 시각'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시각'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='이 댓글이 달린 글'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.tag', verbose_name='태그'),
        ),
    ]
