# Generated by Django 4.2.7 on 2023-11-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User', max_length=20, unique=True),
        ),
    ]
