# Generated by Django 4.2.7 on 2023-11-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
