# Generated by Django 4.2.5 on 2023-11-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_tags_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        # migrations.AlterField(
        #     model_name='comment',
        #     name='tags',
        #     field=models.ManyToManyField(blank=True, to='blog.tag'),
        # ),
        # migrations.AlterField(
        #     model_name='post',
        #     name='tags',
        #     field=models.ManyToManyField(blank=True, to='blog.tag'),
        # ),
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
    ]
