# Generated by Django 4.2 on 2023-12-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chat_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='role',
            field=models.CharField(choices=[('assistant', 'character'), ('user', 'user')], max_length=10),
        ),
    ]
