# Generated by Django 4.2 on 2023-12-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chat_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='first_message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='role',
            field=models.CharField(choices=[('assistant', 'assistant'), ('user', 'user')], max_length=10),
        ),
    ]
