# Generated by Django 3.2.6 on 2023-11-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_comment_tag_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='post',
            new_name='posts',
        ),
    ]
