# Generated by Django 3.2.6 on 2023-11-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_field_name_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
