# Generated by Django 3.2.6 on 2023-11-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_related_name_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
