# Generated by Django 4.2.7 on 2023-11-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_comment_is_updated_comment_tags_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
