# Generated by Django 4.2.7 on 2023-11-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_tag_id_alter_tag_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Please separate your tags with #', to='posts.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Please separate your tags with #', to='posts.tag'),
        ),
    ]
