# Generated by Django 3.2.21 on 2023-11-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231104_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feeling',
        ),
    ]
