# Generated by Django 4.2.7 on 2023-11-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('content', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('comment', models.ManyToManyField(related_name='tagComment', related_query_name='tags', to='blog.comment')),
                ('post', models.ManyToManyField(related_name='tagPost', related_query_name='tags', to='blog.post')),
            ],
        ),
        migrations.RemoveField(
            model_name='tagpost',
            name='post',
        ),
        migrations.DeleteModel(
            name='TagComment',
        ),
        migrations.DeleteModel(
            name='TagPost',
        ),
    ]
