# Generated by Django 4.2 on 2023-12-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_description',
            field=models.TextField(null=True),
        ),
    ]
