# Generated by Django 4.2 on 2023-12-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_character_character_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
